import { NextResponse } from 'next/server';

type Route = { path: string; name: string; purpose: string; sections: string[] };
type Blueprint = { title: string; summary: string; brand: { mood: string; palette: { name: string; hex: string; usage: string }[]; fonts: { display: string; body: string } }; routes: Route[]; components: string[]; visualPrompt: string; threeDEffect: { scene: string; objects: string[]; motion: string }; buildPlan: string[]; qualityChecks: string[] };

function slug(path: string, fallback: string) { return path.replace(/^\//, '').replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || fallback; }
function escape(value: string) { return value.replace(/`/g, '\\`').replace(/\$/g, '\\$'); }

export async function POST(request: Request) {
  try {
    const { blueprint } = (await request.json()) as { blueprint?: Blueprint };
    if (!blueprint?.title || !Array.isArray(blueprint.routes) || blueprint.routes.length === 0) return NextResponse.json({ error: 'A valid blueprint with routes is required.' }, { status: 400 });
    const files: { path: string; content: string }[] = [];
    const palette = blueprint.brand.palette.map((color) => `  --${slug(color.name, 'accent')}: ${color.hex};`).join('\n');
    files.push({ path: 'package.json', content: JSON.stringify({ name: slug(blueprint.title, 'luxe-site'), private: true, scripts: { dev: 'next dev', build: 'next build', start: 'next start' }, dependencies: { next: '14.2.15', react: '18.3.1', 'react-dom': '18.3.1', 'framer-motion': '^11.11.11' } }, null, 2) });
    files.push({ path: 'app/globals.css', content: `@import url('https://fonts.googleapis.com/css2?family=${encodeURIComponent(blueprint.brand.fonts.display)}:wght@400;500;600;700&family=${encodeURIComponent(blueprint.brand.fonts.body)}:wght@400;500;600&display=swap');\n\n:root {\n${palette}\n  --ink: #f8fafc;\n  --surface: #080a13;\n}\n* { box-sizing: border-box; } body { margin: 0; background: var(--surface); color: var(--ink); font-family: '${escape(blueprint.brand.fonts.body)}', sans-serif; } h1,h2,h3 { font-family: '${escape(blueprint.brand.fonts.display)}', sans-serif; }\n` });
    files.push({ path: 'app/layout.tsx', content: `import './globals.css';\nexport default function RootLayout({ children }: { children: React.ReactNode }) { return <html lang="en"><body>{children}</body></html>; }\n` });
    const routeFiles = blueprint.routes.map((route, index) => {
      const routeSlug = slug(route.path, index === 0 ? 'home' : `page-${index + 1}`);
      const sections = route.sections.map((section) => `<section className="section"><span className="eyebrow">${escape(blueprint.title)}</span><h2>${escape(section)}</h2><p>${escape(route.purpose)}</p></section>`).join('');
      const content = `'use client';\nimport { motion } from 'framer-motion';\nexport default function ${routeSlug.replace(/[^a-z0-9]/gi, '') || 'Page'}() { return <main className="shell"><nav><strong>${escape(blueprint.title)}</strong><span>${escape(route.name)}</span></nav><motion.header initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }}><p className="eyebrow">${escape(blueprint.brand.mood)}</p><h1>${escape(route.name)}</h1><p>${escape(route.purpose)}</p></motion.header>${sections}<footer>${escape(blueprint.threeDEffect.scene)} · ${escape(blueprint.threeDEffect.motion)}</footer></main>; }\n`;
      return { path: `app/${routeSlug === 'home' ? '' : `${routeSlug}/`}page.tsx`, content };
    });
    files.push(...routeFiles);
    files.push({ path: 'README.md', content: `# ${blueprint.title}\n\nGenerated by Codex+ Luxe Studio.\n\nVisual direction: ${blueprint.visualPrompt}\n\n3D direction: ${blueprint.threeDEffect.scene}. ${blueprint.threeDEffect.motion}\n` });
    return NextResponse.json({ files, count: files.length, provider: 'codex-local-scaffold' });
  } catch { return NextResponse.json({ error: 'Unable to generate the project files.' }, { status: 500 }); }
}
